variables:
  FRONT_DIR: /root/frontend_dev
  PROD_FRONT_DIR: /root/frontend_prod
  GIT_SSL_NO_VERIFY: "1"

stages:
- deploy

deploy_dev:
  stage: deploy
  tags:
    - frontend
  only:
    - dev
  script:
    - sudo rsync -avz --delete ./ $FRONT_DIR
    - sudo sh -c "cd $FRONT_DIR && docker-compose -f docker-compose.dev.yaml up --build -d
  
deploy_prod:
  stage: deploy
  tags:
    - frontend
  only:
    - stable
  script:
    - sudo rsync -avz --delete ./ $PROD_FRONT_DIR
    - sudo sh -c "cd $PROD_FRONT_DIR && docker-compose -f docker-compose.yaml up --build -d
  
