version: "3"
services:
  aiddn:
    container_name: aiddn_front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      NODE_ENV: production
    command: bash -c "cd /app && ls && npm run start"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"